name: subsmanager
description: Subscription Manager

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 < 3.0.1"

dependencies:
  flutter:
    sdk: flutter
  
  awesome_notifications: ^0.6.21
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^1.0.4
  modal_bottom_sheet: ^2.0.1
  flutter_rounded_date_picker: ^3.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dropdown_button2: ^1.5.1
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  flutter_local_notifications: ^9.6.0
  shared_preferences: ^2.0.15
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17
  cloud_firestore: ^3.1.17
  connectivity_plus: ^1.0.6
  package_info_plus: ^1.4.2
  json_annotation: ^4.5.0
  uuid: ^3.0.6
  flutter_markdown: ^0.6.10+2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  generate: false
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/privacy_policy/privacy_policy_ja.md

  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: lib/assets/fonts/NotoSansJP-Regular.otf
  
flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/icon.png
